### ISSUE TITLE
[New Blog]: r-ladiesmelbourne blog! 

### ISSUE THREAD

**Issue by dionnecargy** [rladies/awesome-rladies-blogs#111]
### Blog Name

R-Ladies Melbourne Blog

### Blog URL

https://r-ladiesmelbourne.github.io/blog_index.html

### Author Name

R-Ladies Melbourne

### Author Twitter Username

rladiesmelb

### Author GitHub Username

r-ladiesmelbourne

### Code of Conduct

- [X] I agree to follow R-Ladies' Code of Conduct

**Comment by cosimameyer** [comment]
Hi @dionnecargy,

Thanks so much for opening the issue (and welcome!) 🎉 

I’ll look into it later today but some quick questions: 
- Do you want to add your bluesky and/or mastodon handle as well? (it’s not reflected in our automatic issue form yet) 
- the blog URL you shared is also your RSS feed - just to confirm: is it ok for me to put it in the RSS feed so that the bot can pick up your posts and share them?  
- do you want to be added to the bluesky starter pack of R-Ladies as well? ☺️

**Comment by dionnecargy** [comment]
Hi @cosimameyer than you so so much! (1) Yes that would be amazing if you could add our bluesky handle, (2) yes please, and (3) yes yes yes!

**Comment by cosimameyer** [comment]
Merged in #113
